.PHONY: clean All

All:
	@echo "----------Building project:[ PAC4_PEC4 - Debug ]----------"
	@cd "PAC4_PEC4" && "$(MAKE)" -f  "PAC4_PEC4.mk"
clean:
	@echo "----------Cleaning project:[ PAC4_PEC4 - Debug ]----------"
	@cd "PAC4_PEC4" && "$(MAKE)" -f  "PAC4_PEC4.mk" clean
